### ISSUE TITLE
Error when Solo?

### ISSUE THREAD

**Issue by 5aaee9** [MatthewClair/l4d2readyup#20]
I was play the game with plguin commit 4af9c6de4dfa52b342fc809c7cf67f8eb08fe6a9
When I was enabled this plugins and I am ready, the game is not start.
![image](https://cloud.githubusercontent.com/assets/7685264/17507021/d23bc7c2-5e3f-11e6-9824-9c81bffe48c1.png)

```
SourceMod Version Information:
    SourceMod Version: 1.7.3-dev+5303
    SourcePawn Engine: SourcePawn 1.7, jit-x86 (build 1.7.3-dev+5303)
    SourcePawn API: v1 = 4, v2 = 6
    Compiled on: Apr 21 2016 13:21:28
    Built from: https://github.com/alliedmodders/sourcemod/commit/6317916
    Build ID: 5303:6317916
    http://www.sourcemod.net/
```

**Comment by MatthewClair** [comment]
The plugin doesn't support bots.  It is mainly targeting competitive versus that has two full teams.  If you need to start it before the normal ready condition, you can use `!forcestart` and it will initiate the round as if everyone was present and ready.

**Comment by 5aaee9** [comment]
@MatthewClair Thanks
