### ISSUE TITLE
Error compil

### ISSUE THREAD

**Issue by Owned67** [MatthewClair/l4d2readyup#3]
Error compiled : //// readyup.sp
// G:\L4D2\War\ProMod-master\addons\sourcemod\scripting\include\l4d2_direct.inc(
577) : warning 209: function "L4D2Direct_GetPreIncapHealth" should return a valu
e
// G:\L4D2\War\ProMod-master\addons\sourcemod\scripting\include\l4d2_direct.inc(
579) : error 078: function uses both "return" and "return <value>"
// G:\L4D2\War\ProMod-master\addons\sourcemod\scripting\include\l4d2_direct.inc(
608) : warning 209: function "L4D2Direct_GetPreIncapHealthBuffer" should return
a value
// G:\L4D2\War\ProMod-master\addons\sourcemod\scripting\include\l4d2_direct.inc(
610) : error 078: function uses both "return" and "return <value>"
//
// 2 Errors.
//
// Compilation Time: 0,31 sec
// ----------------------------------------

**Comment by MatthewClair** [comment]
You need the includes from the [sm160 branch of l4d2_direct](https://github.com/ConfoglTeam/l4d2_direct/tree/sm160/)
